"""Train the artifact consumed by the local FastAPI prediction service."""
from __future__ import annotations

import json
from pathlib import Path

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import average_precision_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

ROOT = Path(__file__).resolve().parent.parent
DATASET_PATH = ROOT / "dataset" / "upi_transactions_2024.csv"
ARTIFACT_PATH = Path(__file__).with_name("failure_predictor.joblib")
REPORT_PATH = Path(__file__).with_name("model_report.json")
CATEGORICAL_COLUMNS = ["transaction_type", "merchant_category", "sender_age_group", "receiver_age_group", "sender_state", "sender_bank", "receiver_bank", "device_type", "network_type", "day_of_week"]
NUMERIC_COLUMNS = ["amount_inr", "hour_of_day", "fraud_flag", "is_weekend", "is_peak_hour", "is_night", "is_high_value"]
FEATURE_COLUMNS = CATEGORICAL_COLUMNS + NUMERIC_COLUMNS


def feature_frame(data: pd.DataFrame) -> pd.DataFrame:
    """Create exactly the columns generated by ``ml/app.py``."""
    amount = pd.to_numeric(data["amount (INR)"], errors="coerce")
    hour = pd.to_numeric(data["hour_of_day"], errors="coerce").fillna(0).astype(int)
    return pd.DataFrame({
        "transaction_type": data["transaction_type"].astype(str),
        "merchant_category": data["merchant_category"].astype(str),
        "sender_age_group": data["sender_age_group"].astype(str),
        "receiver_age_group": data["receiver_age_group"].astype(str),
        "sender_state": data["sender_state"].astype(str),
        "sender_bank": data["sender_bank"].astype(str),
        "receiver_bank": data["receiver_bank"].astype(str),
        "device_type": data["device_type"].astype(str),
        "network_type": data["network_type"].astype(str),
        "day_of_week": data["day_of_week"].astype(str),
        "amount_inr": amount, "hour_of_day": hour,
        "fraud_flag": pd.to_numeric(data["fraud_flag"], errors="coerce"),
        "is_weekend": pd.to_numeric(data["is_weekend"], errors="coerce"),
        "is_peak_hour": hour.isin([9, 10, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22]).astype(int),
        "is_night": hour.between(0, 6).astype(int), "is_high_value": (amount > 10000).astype(int),
    })[FEATURE_COLUMNS]


def main() -> None:
    data = pd.read_csv(DATASET_PATH)
    features = feature_frame(data)
    target = (data["transaction_status"].astype(str) != "SUCCESS").astype(int)
    x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42, stratify=target)
    preprocessor = ColumnTransformer([
        ("categorical", Pipeline([("imputer", SimpleImputer(strategy="most_frequent")), ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))]), CATEGORICAL_COLUMNS),
        ("numeric", SimpleImputer(strategy="median"), NUMERIC_COLUMNS),
    ])
    model = Pipeline([("preprocess", preprocessor), ("classifier", HistGradientBoostingClassifier(random_state=42))])
    model.fit(x_train, y_train)
    probabilities = model.predict_proba(x_test)[:, 1]
    metrics = {"roc_auc": round(float(roc_auc_score(y_test, probabilities)), 6), "average_precision": round(float(average_precision_score(y_test, probabilities)), 6)}
    artifact = {"model": model, "model_name": "hist_gradient_boosting", "feature_columns": FEATURE_COLUMNS, "target_definition": "transaction_status != SUCCESS", "metrics": metrics}
    joblib.dump(artifact, ARTIFACT_PATH)
    REPORT_PATH.write_text(json.dumps({"dataset_rows": int(len(data)), "selected_model": artifact["model_name"], "test_metrics": metrics, "artifact": ARTIFACT_PATH.name}, indent=2), encoding="utf-8")
    print(f"Saved {ARTIFACT_PATH.name}; test metrics: {metrics}")


if __name__ == "__main__":
    main()
