-- RecoverFlow: AI Revenue Recovery Agent Database Schema
-- For Razorpay AI Buildathon
-- Designed for production use with optimized indexes and foreign key relationships

CREATE DATABASE IF NOT EXISTS recoverflow;
USE recoverflow;

-- ============================================================================
-- 1. PAYMENT_EVENTS: Raw incoming payment webhooks from Razorpay
-- ============================================================================
CREATE TABLE IF NOT EXISTS payment_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(128) UNIQUE NOT NULL COMMENT 'Razorpay webhook event_id',
    payment_id VARCHAR(128) NOT NULL COMMENT 'Razorpay payment_id',
    order_id VARCHAR(128) COMMENT 'Razorpay order_id (if applicable)',
    amount DECIMAL(10, 2) NOT NULL COMMENT 'Payment amount in base units',
    currency VARCHAR(3) DEFAULT 'INR' COMMENT 'Currency code',
    status ENUM('failed', 'captured', 'authorized', 'refunded', 'pending') NOT NULL,
    gateway VARCHAR(50) COMMENT 'Payment gateway (e.g., RAZORPAY, HDFC, ICICI)',
    bank_or_wallet VARCHAR(100) COMMENT 'Issuing bank or wallet provider',
    error_code VARCHAR(50) COMMENT 'Razorpay error code if failed',
    error_description TEXT COMMENT 'Human-readable error message',
    customer_id VARCHAR(128) COMMENT 'Customer identifier',
    raw_payload JSON NOT NULL COMMENT 'Complete webhook payload from Razorpay',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE KEY uk_event_id (event_id),
    INDEX idx_payment_id (payment_id),
    INDEX idx_order_id (order_id),
    INDEX idx_status (status),
    INDEX idx_customer_id (customer_id),
    INDEX idx_created_at (created_at),
    INDEX idx_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores raw payment webhook events from Razorpay';

-- ============================================================================
-- 2. SYSTEM_INSIGHTS: ML Model and Degradation Engine outputs
-- ============================================================================
CREATE TABLE IF NOT EXISTS system_insights (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    payment_event_id BIGINT NOT NULL,
    failure_probability DECIMAL(5, 4) COMMENT 'ML score 0-1: likelihood of failure reoccurrence',
    degradation_status ENUM('healthy', 'degraded', 'critical') DEFAULT 'healthy' COMMENT 'System health status',
    affected_gateway VARCHAR(50) COMMENT 'Specific gateway experiencing issues',
    affected_bank VARCHAR(100) COMMENT 'Specific bank experiencing issues',
    root_cause_category ENUM(
        'gateway_issue', 
        'bank_issue', 
        'customer_issue', 
        'network_issue',
        'rate_limit',
        'timeout',
        'insufficient_funds',
        'invalid_card',
        'unknown'
    ) DEFAULT 'unknown' COMMENT 'Categorized root cause',
    model_confidence DECIMAL(5, 4) COMMENT 'Confidence score of degradation analysis',
    model_version VARCHAR(20) COMMENT 'Version of ML model used',
    additional_metadata JSON COMMENT 'Additional insights (retry_recommended, wait_duration_seconds, etc.)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_payment_event FOREIGN KEY (payment_event_id) 
        REFERENCES payment_events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    INDEX idx_payment_event_id (payment_event_id),
    INDEX idx_degradation_status (degradation_status),
    INDEX idx_affected_gateway (affected_gateway),
    INDEX idx_root_cause (root_cause_category),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores ML model outputs and system degradation analysis';

-- Keep this enum aligned with RootCauseCategory in the backend.
ALTER TABLE system_insights MODIFY COLUMN root_cause_category ENUM(
    'gateway_issue', 'bank_issue', 'customer_issue', 'network_issue',
    'temporary_network', 'timeout', 'rate_limit', 'insufficient_funds',
    'invalid_card', 'card_expired', 'authentication_failure', 'upi_failure',
    'repeated_failure', 'unknown'
) DEFAULT 'unknown';

-- ============================================================================
-- 3. AI_AGENT_ANALYSIS: AI Agent's root cause analysis and recovery strategy
-- ============================================================================
CREATE TABLE IF NOT EXISTS ai_agent_analysis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    payment_event_id BIGINT NOT NULL,
    system_insight_id BIGINT COMMENT 'Link to ML insights',
    confidence_score DECIMAL(5, 4) NOT NULL COMMENT 'AI confidence 0-1 in suggested strategy',
    root_cause_analysis TEXT NOT NULL COMMENT 'Detailed RCA generated by AI',
    generated_explanation TEXT COMMENT 'Human-readable explanation for stakeholders',
    suggested_channel ENUM(
        'retry', 
        'payment_link', 
        'notification', 
        'customer_support', 
        'none'
    ) DEFAULT 'none' COMMENT 'Recommended recovery action channel',
    suggested_amount DECIMAL(10, 2) COMMENT 'Amount to attempt recovery for (may differ from original)',
    retry_strategy JSON COMMENT 'Details: retry_count, retry_delay_seconds, backoff_multiplier',
    recovery_strategy JSON COMMENT 'Structured recovery strategy (timing, channel, conditions)',
    ai_model_name VARCHAR(100) COMMENT 'Name/version of AI model used',
    reasoning_chain JSON COMMENT 'Step-by-step reasoning for auditability',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_payment_event_analysis FOREIGN KEY (payment_event_id)
        REFERENCES payment_events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_system_insight FOREIGN KEY (system_insight_id)
        REFERENCES system_insights(id) ON DELETE SET NULL ON UPDATE CASCADE,
    
    INDEX idx_payment_event_id (payment_event_id),
    INDEX idx_system_insight_id (system_insight_id),
    INDEX idx_suggested_channel (suggested_channel),
    INDEX idx_confidence_score (confidence_score),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores AI agent analysis and recovery strategy recommendations';

-- ============================================================================
-- 4. RECOVERY_ACTIONS: Rules Engine output and action execution
-- ============================================================================
CREATE TABLE IF NOT EXISTS recovery_actions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ai_agent_analysis_id BIGINT NOT NULL COMMENT 'Link to AI strategy',
    payment_event_id BIGINT NOT NULL COMMENT 'Link to original failed payment',
    action_type ENUM(
        'retry', 
        'payment_link', 
        'notification', 
        'customer_support', 
        'none'
    ) NOT NULL COMMENT 'Type of recovery action',
    execution_status ENUM('triggered', 'pending', 'executed', 'failed', 'cancelled') DEFAULT 'pending',
    new_razorpay_link_id VARCHAR(128) COMMENT 'New payment link ID (if action_type=payment_link)',
    new_payment_id VARCHAR(128) COMMENT 'New payment ID created for recovery attempt',
    action_metadata JSON COMMENT 'Action-specific data: retry_count, link_expiry, sms_template_id, etc.',
    rules_applied VARCHAR(255) COMMENT 'Comma-separated list of business rules that triggered this action',
    execution_error TEXT COMMENT 'Error message if execution failed',
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When action was triggered',
    executed_at TIMESTAMP NULL COMMENT 'When action was actually executed',
    
    CONSTRAINT fk_ai_agent_analysis FOREIGN KEY (ai_agent_analysis_id)
        REFERENCES ai_agent_analysis(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payment_event_action FOREIGN KEY (payment_event_id)
        REFERENCES payment_events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    INDEX idx_ai_agent_analysis_id (ai_agent_analysis_id),
    INDEX idx_payment_event_id (payment_event_id),
    INDEX idx_new_payment_id (new_payment_id),
    INDEX idx_execution_status (execution_status),
    INDEX idx_action_type (action_type),
    INDEX idx_triggered_at (triggered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores recovery actions executed by the Rules Engine';

-- ============================================================================
-- 5. RECOVERY_OUTCOMES: Feedback loop mapping recovery success
-- ============================================================================
CREATE TABLE IF NOT EXISTS recovery_outcomes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    recovery_action_id BIGINT NOT NULL COMMENT 'Link to recovery action',
    original_payment_event_id BIGINT NOT NULL COMMENT 'Link to original failed payment',
    new_payment_event_id BIGINT COMMENT 'Link to successful payment (if recovered)',
    outcome_status ENUM(
        'success', 
        'failed', 
        'pending', 
        'timeout', 
        'cancelled',
        'partial'
    ) DEFAULT 'pending' COMMENT 'Overall outcome of recovery attempt',
    recovery_success BOOLEAN COMMENT 'TRUE if recovery succeeded (payment.captured received)',
    recovered_amount DECIMAL(10, 2) COMMENT 'Amount successfully recovered',
    recovery_attempt_count INT DEFAULT 1 COMMENT 'How many recovery attempts were made',
    time_to_recovery INT COMMENT 'Seconds elapsed from action trigger to successful payment.captured',
    recovery_velocity_hours DECIMAL(5, 2) COMMENT 'Hours between original failure and recovery',
    feedback_notes JSON COMMENT 'Notes, flags, and observations (customer_feedback, manual_intervention_needed, etc.)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_recovery_action FOREIGN KEY (recovery_action_id)
        REFERENCES recovery_actions(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_original_payment FOREIGN KEY (original_payment_event_id)
        REFERENCES payment_events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_new_payment FOREIGN KEY (new_payment_event_id)
        REFERENCES payment_events(id) ON DELETE SET NULL ON UPDATE CASCADE,
    
    INDEX idx_recovery_action_id (recovery_action_id),
    INDEX idx_original_payment_id (original_payment_event_id),
    INDEX idx_new_payment_id (new_payment_event_id),
    INDEX idx_outcome_status (outcome_status),
    INDEX idx_recovery_success (recovery_success),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores recovery outcomes and completes the feedback loop';

-- ============================================================================
-- HELPFUL VIEWS FOR ANALYTICS
-- ============================================================================

-- View 1: Complete Recovery Pipeline
CREATE OR REPLACE VIEW v_recovery_pipeline AS
SELECT 
    pe.id AS payment_event_id,
    pe.payment_id,
    pe.order_id,
    pe.amount,
    pe.status AS payment_status,
    pe.error_code,
    si.root_cause_category,
    si.failure_probability,
    aa.confidence_score,
    aa.suggested_channel,
    ra.action_type,
    ra.execution_status,
    ro.recovery_success,
    ro.time_to_recovery,
    pe.created_at AS failure_time,
    ro.updated_at AS outcome_time
FROM payment_events pe
LEFT JOIN system_insights si ON pe.id = si.payment_event_id
LEFT JOIN ai_agent_analysis aa ON pe.id = aa.payment_event_id
LEFT JOIN recovery_actions ra ON aa.id = ra.ai_agent_analysis_id
LEFT JOIN recovery_outcomes ro ON ra.id = ro.recovery_action_id
WHERE pe.status = 'failed';

-- View 2: Recovery Success Rate Dashboard
CREATE OR REPLACE VIEW v_recovery_metrics AS
SELECT 
    DATE(ro.created_at) AS recovery_date,
    COUNT(*) AS total_recovery_attempts,
    SUM(CASE WHEN ro.recovery_success = TRUE THEN 1 ELSE 0 END) AS successful_recoveries,
    SUM(CASE WHEN ro.recovery_success = FALSE THEN 1 ELSE 0 END) AS failed_recoveries,
    ROUND(100.0 * SUM(CASE WHEN ro.recovery_success = TRUE THEN 1 ELSE 0 END) / COUNT(*), 2) AS success_rate_pct,
    SUM(ro.recovered_amount) AS total_recovered_amount,
    AVG(ro.time_to_recovery) AS avg_recovery_time_seconds
FROM recovery_outcomes ro
WHERE ro.outcome_status IN ('success', 'failed')
GROUP BY DATE(ro.created_at);

-- ============================================================================
-- SAMPLE QUERIES FOR COMMON USE CASES
-- ============================================================================

-- Find all failed payments awaiting recovery
-- SELECT * FROM payment_events 
-- WHERE status = 'failed' 
--   AND created_at > DATE_SUB(NOW(), INTERVAL 7 DAY)
-- ORDER BY created_at DESC;

-- Check recovery status for a specific order
-- SELECT * FROM v_recovery_pipeline 
-- WHERE order_id = 'order_xyz' 
-- ORDER BY failure_time DESC;

-- Dashboard: Today's recovery metrics
-- SELECT * FROM v_recovery_metrics 
-- WHERE recovery_date = CURDATE();

-- Find recoveries that took longest
-- SELECT recovery_action_id, original_payment_event_id, 
--        time_to_recovery, recovery_success 
-- FROM recovery_outcomes 
-- WHERE recovery_success = TRUE 
-- ORDER BY time_to_recovery DESC 
-- LIMIT 10;
